<?php

namespace ContainerGIIiS0s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N46KRZWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n46KRZW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n46KRZW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'trickGroupRepository' => ['privates', 'App\\Repository\\TrickGroupRepository', 'getTrickGroupRepositoryService', true],
        ], [
            'entityManagerInterface' => '?',
            'trickGroupRepository' => 'App\\Repository\\TrickGroupRepository',
        ]);
    }
}
