<?php

namespace ContainerGIIiS0s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UFCOin_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uFCOin.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uFCOin.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.7pbQgVP', 'get_ServiceLocator_7pbQgVPService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\TrickController::addTrick' => ['privates', '.service_locator.n46KRZW', 'get_ServiceLocator_N46KRZWService', true],
            'App\\Controller\\TrickController::deleteTrick' => ['privates', '.service_locator.tt1MTrX', 'get_ServiceLocator_Tt1MTrXService', true],
            'App\\Controller\\TrickController::displayAllTricks' => ['privates', '.service_locator.t1acvuo', 'get_ServiceLocator_T1acvuoService', true],
            'App\\Controller\\TrickController::displayTrick' => ['privates', '.service_locator.tt1MTrX', 'get_ServiceLocator_Tt1MTrXService', true],
            'App\\Controller\\TrickController::loadMoreComments' => ['privates', '.service_locator.t1acvuo', 'get_ServiceLocator_T1acvuoService', true],
            'App\\Controller\\TrickController::loadMoreTricks' => ['privates', '.service_locator.t1acvuo', 'get_ServiceLocator_T1acvuoService', true],
            'App\\Controller\\TrickController::modifyTrick' => ['privates', '.service_locator.mPAO.Fx', 'get_ServiceLocator_MPAO_FxService', true],
            'App\\Controller\\UserProfileController::modifyProfile' => ['privates', '.service_locator.6_RE8XY', 'get_ServiceLocator_6RE8XYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.7pbQgVP', 'get_ServiceLocator_7pbQgVPService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\TrickController:addTrick' => ['privates', '.service_locator.n46KRZW', 'get_ServiceLocator_N46KRZWService', true],
            'App\\Controller\\TrickController:deleteTrick' => ['privates', '.service_locator.tt1MTrX', 'get_ServiceLocator_Tt1MTrXService', true],
            'App\\Controller\\TrickController:displayAllTricks' => ['privates', '.service_locator.t1acvuo', 'get_ServiceLocator_T1acvuoService', true],
            'App\\Controller\\TrickController:displayTrick' => ['privates', '.service_locator.tt1MTrX', 'get_ServiceLocator_Tt1MTrXService', true],
            'App\\Controller\\TrickController:loadMoreComments' => ['privates', '.service_locator.t1acvuo', 'get_ServiceLocator_T1acvuoService', true],
            'App\\Controller\\TrickController:loadMoreTricks' => ['privates', '.service_locator.t1acvuo', 'get_ServiceLocator_T1acvuoService', true],
            'App\\Controller\\TrickController:modifyTrick' => ['privates', '.service_locator.mPAO.Fx', 'get_ServiceLocator_MPAO_FxService', true],
            'App\\Controller\\UserProfileController:modifyProfile' => ['privates', '.service_locator.6_RE8XY', 'get_ServiceLocator_6RE8XYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TrickController::addTrick' => '?',
            'App\\Controller\\TrickController::deleteTrick' => '?',
            'App\\Controller\\TrickController::displayAllTricks' => '?',
            'App\\Controller\\TrickController::displayTrick' => '?',
            'App\\Controller\\TrickController::loadMoreComments' => '?',
            'App\\Controller\\TrickController::loadMoreTricks' => '?',
            'App\\Controller\\TrickController::modifyTrick' => '?',
            'App\\Controller\\UserProfileController::modifyProfile' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TrickController:addTrick' => '?',
            'App\\Controller\\TrickController:deleteTrick' => '?',
            'App\\Controller\\TrickController:displayAllTricks' => '?',
            'App\\Controller\\TrickController:displayTrick' => '?',
            'App\\Controller\\TrickController:loadMoreComments' => '?',
            'App\\Controller\\TrickController:loadMoreTricks' => '?',
            'App\\Controller\\TrickController:modifyTrick' => '?',
            'App\\Controller\\UserProfileController:modifyProfile' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
