<?php

namespace ContainerGIIiS0s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrickGroupTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TrickGroupType' shared autowired service.
     *
     * @return \App\Form\TrickGroupType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TrickGroupType.php';

        return $container->privates['App\\Form\\TrickGroupType'] = new \App\Form\TrickGroupType();
    }
}
