version: '2'

services:
  myapp:
    image: 'bitnami/symfony:1'
    container_name: symfony
    ports:
      - '8000:8000'
    volumes:
      - '${PROJECT_PATH}Symfony:/app'
    environment:
      - SYMFONY_PROJECT_NAME=myapp
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=bobby
      - MARIADB_PASSWORD=tables
      - MARIADB_DATABASE=myapp
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.3'
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bobby
      - MARIADB_PASSWORD=tables
      - MARIADB_DATABASE=SnowTricksDB
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8001:80
  smtp:
    image: mwader/postfix-relay
    container_name: smtp
    environment:
      - POSTFIX_myhostname=smtp.yopmail.com
      - OPENDKIM_DOMAINS=yopmail.com