<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPzCnhK6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPzCnhK6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPzCnhK6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPzCnhK6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPzCnhK6\App_KernelDevDebugContainer([
    'container.build_hash' => 'PzCnhK6',
    'container.build_id' => 'ab6a96a8',
    'container.build_time' => 1643556042,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPzCnhK6');
