<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGIIiS0s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGIIiS0s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGIIiS0s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGIIiS0s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGIIiS0s\App_KernelDevDebugContainer([
    'container.build_hash' => 'GIIiS0s',
    'container.build_id' => '317495c6',
    'container.build_time' => 1642196661,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGIIiS0s');
